name: Backend Continuous Integration

on:
  pull_request:
    branches: [main]
    paths: [starter/backend/**]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install Dependencies
        working-directory: starter/backend
        run: |
          pip install flake8
          pipenv install --dev
      - name: Run Linter
        working-directory: starter/backend
        run: |
          pipenv run flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install Dependencies
        working-directory: starter/backend
        run: |
          pip install pytest
          pipenv install
      - name: Run Tests
        working-directory: starter/backend
        run: |
          pipenv run python -m pytest