name: Backend Continuous Deployment

on:
  push:
    branches: [main]
    paths: [starter/backend/**]
  workflow_dispatch:

env:
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Docker Image
        run: |
          cd starter/backend
          docker buildx create --name mybuilder || true
          docker buildx use mybuilder
          docker buildx build \
            --platform=linux/amd64 \
            -t ${{ env.ECR_REGISTRY }}/backend:${GITHUB_SHA} \
            --push .