name: Backend Continuous Integration

on:
  pull_request:
    branches: [main]
    paths: [starter/backend/**]  # Updated path

  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: pip
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install Dependencies
        working-directory: starter/backend
        run: |
          pipenv install --dev
      - name: Run Linter
        working-directory: starter/backend
        run: pipenv run flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: pip
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install Dependencies
        working-directory: starter/backend
        run: |
          pipenv install
      - name: Run Tests
        working-directory: starter/backend
        run: |
          pipenv run python -m pytest

  build:
    runs-on: ubuntu-latest
    needs: [linting, test]
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        working-directory: starter/backend
        run: |
          docker build -t backend:ci .